root/routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Auth::routes();

Route::middleware(['auth'])->group(function(){
    Route::get('/', 'HomeController@index')->name('home');
    Route::resource('/keywords', 'KeywordController');
    Route::post('/generate', 'HomeController@generate')->name('generate');
    Route::resource('/account', 'UserController');
});

root/app/Keyword.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Keyword extends Model
{
    //
}

root/app/Http/Controllers/KeywordController.php
<?php

namespace App\Http\Controllers;

use App\Keyword;
use League\Csv\Reader;
use League\Csv\Statement;

use Illuminate\Http\Request;

class KeywordController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $keywords = Keyword::get();
        return view('keywords.index',['keywords'=>$keywords]);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        //
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $request->validate(
            [
                'keyword'=>"required_without:keyword_upload|string|unique:keywords",
                'keyword_upload'=>"required_without:keyword|file"
            ]
        );
        if($request->keyword){
            $keyword = new Keyword;
            $keyword->keyword = $request->keyword;
            $keyword->save();
            return redirect()->back()->with(['success'=>"New Keyword Created"]);
        }
        elseif($request->hasFile('keyword_upload')){
            $csv = Reader::createFromPath($request->file('keyword_upload'), 'r');
            $uploaded = 0;
            $created  = 0;
            foreach ($csv as $item) {
                $uploaded++;
                $check =Keyword::where('keyword',$item[0])->first();
                if(!$check){
                    $keyword = new Keyword;
                    $keyword->keyword = $item[0];
                    $keyword->save();                
                    $created++;
                }
            }
            return redirect()->back()->with(['success'=>"$created/$uploaded Keywords created."]);
        }
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\Keyword  $keyword
     * @return \Illuminate\Http\Response
     */
    public function show(Keyword $keyword)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Keyword  $keyword
     * @return \Illuminate\Http\Response
     */
    public function edit(Keyword $keyword)
    {
        
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\Keyword  $keyword
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, Keyword $keyword)
    {
        $request->validate(
            ['keyword'=>"required|string|unique:keywords,keyword,$keyword->id"]
        );
        $keyword->keyword = $request->keyword;
        $keyword->save();
        return redirect()->back()->with(['success'=>"Keyword Updated"]);
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Keyword  $keyword
     * @return \Illuminate\Http\Response
     */
    public function destroy(Keyword $keyword)
    {
       $keyword->delete();
       return redirect()->back()->with(['success'=>"Keyword Deleted"]);
    }
}

root/resources/views/keywords/add.blade.php
<!-- The Modal -->
<div class="modal" id="add-keyword">
  <form action="{{route('keywords.store')}}" method="POST" class="modal-dialog modal-dialog-centered modal-sm">
    @csrf
    <div class="modal-content">

      <!-- Modal Header -->
      <div class="modal-header">
        <strong class="modal-title">Add Keyword</strong>
      </div>

      <!-- Modal body -->
      <div class="modal-body">
        <div class="form-group">
            <label for="keyword">Keyword</label>
            <input type="text" required name="keyword" id="keyword" class="form-control">
        </div>
      </div>

      <!-- Modal footer -->
      <div class="modal-footer">
        <button type="submit" class="btn btn-success">Save</button>
        <button type="button" class="btn btn-default" data-dismiss="modal">Cancel</button>
      </div>
    </div>
</form>
</div>

root/resources/views/keywords/bulk.blade.php
<!-- The Modal -->
<div class="modal" id="bulk-keyword">
  <form action="{{route('keywords.store')}}" method="POST" class="modal-dialog modal-dialog-centered modal-sm" enctype="multipart/form-data">
    @csrf
    <div class="modal-content">

      <!-- Modal Header -->
      <div class="modal-header">
        <strong class="modal-title">Bulk Add Keywords</strong>
      </div>

      <!-- Modal body -->
      <div class="modal-body">
        <div class="form-group">
            <label for="keyword_upload">Import File</label>
            <input type="file" required name="keyword_upload" id="keyword_upload" class="form-control" accept=".xls,.xlsx,.csv">
        </div>
      </div>

      <!-- Modal footer -->
      <div class="modal-footer">
        <button type="submit" class="btn btn-success">Upload</button>
        <button type="button" class="btn btn-default" data-dismiss="modal">Cancel</button>
      </div>
    </div>
</form>
</div>

root/resources/views/keywords/edit.blade.php
<!-- The Modal -->
<div class="modal" id="edit-keyword">
  <form action="" id="edit-keyword-form" method="POST" class="modal-dialog modal-dialog-centered modal-sm">
    <input type="hidden" name="_method" value="PUT">
    @csrf
    <div class="modal-content">

      <!-- Modal Header -->
      <div class="modal-header">
        <strong class="modal-title">Edit Keyword</strong>
      </div>

      <!-- Modal body -->
      <div class="modal-body">
        <div class="form-group">
            <label for="keyword_edit">Keyword</label>
            <input type="text" required name="keyword" id="keyword_edit" class="form-control">
        </div>
      </div>

      <!-- Modal footer -->
      <div class="modal-footer">
        <button type="submit" class="btn btn-success">Update</button>
        <button type="button" class="btn btn-default" data-dismiss="modal">Cancel</button>
      </div>
    </div>
</form>
</div>
<script>
$(function(){
    $('#edit-keyword').on('show.bs.modal', function (event) {
      var button    = $(event.relatedTarget)
      var id        = button.data('id')
      var keyword   = button.data('keyword')
      var modal     = $(this)
      modal.find('#keyword_edit').val(keyword)
      modal.find('#edit-keyword-form').attr('action',`{{route('keywords.index')}}/${id}`)
    })
})
</script>

root/resources/views/keywords/index.blade.php
@extends('layouts.app')

@section('content')
<div class="container">
    <div class="py-4"></div>
    <div class="row justify-content-center">
        <div class="col-md-3">
            <div class="btn-group">
                <button data-toggle="modal" data-target="#add-keyword" class="btn btn-success btn-sm">Add Keyword</button>
                <button data-toggle="modal" data-target="#bulk-keyword" class="btn btn-success btn-sm">Import Keywords</button>
            </div>
        </div>
        <div class="col-md-9">
            <h4>Keywords</h4>
            <table class="table table-sm">
                <thead>
                    <tr>
                        <th>Keyword</th>
                        <th>Action</th>
                    </tr>
                </thead>
                <tbody>
                    @foreach ($keywords as $keyword)
                        <tr>
                            <th>{{$keyword->keyword}}</th>
                            <th>
                                <form action="{{route('keywords.destroy',[$keyword])}}" method="post" class="btn-group">
                                    <input type="hidden" name="_method" value="DELETE">
                                    <button data-toggle="modal" data-target="#edit-keyword"  type="button" data-id="{{$keyword->id}}" data-keyword="{{$keyword->keyword}}" class="btn btn-sm">Edit</button>
                                    <button type="submit" class="btn btn-danger btn-sm">Delete</button>
                                    @csrf
                                </form>
                            </th>
                        </tr>
                    @endforeach
                    @empty($keywords->count())
                        <tr>
                            <th class="text-black-50">No Keywords Added</th>
                        </tr>
                    @endempty
                </tbody>
            </table>
        </div>
    </div>
</div>
@include('keywords.add')
@include('keywords.edit')
@include('keywords.bulk')
@endsection