root/routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Auth::routes();

Route::middleware(['auth'])->group(function(){
    Route::get('/', 'HomeController@index')->name('home');
    Route::resource('/keywords', 'KeywordController');
    Route::post('/generate', 'HomeController@generate')->name('generate');
    Route::resource('/account', 'UserController');
});

root/resources/views/generate.blade.php
<!-- The Modal -->
<div class="modal" id="generate">
  <form action="{{route('generate')}}" method="POST" class="modal-dialog modal-dialog-centered modal-sm" enctype="multipart/form-data">
    @csrf
    <div class="modal-content">

      <!-- Modal Header -->
      <div class="modal-header">
        <strong class="modal-title">Generate Keywords</strong>
      </div>

      <!-- Modal body -->
      <div class="modal-body">
        <div class="form-group">
            <label for="upload_generate_file">Import File</label>
            <input type="file" required name="upload_generate_file" id="upload_generate_file" class="form-control" accept=".csv">
        </div>
      </div>

      <!-- Modal footer -->
      <div class="modal-footer">
        <button type="submit" class="btn btn-success">Upload</button>
        <button type="button" class="btn btn-default" data-dismiss="modal">Cancel</button>
      </div>
    </div>
</form>
</div>

root/resources/views/home.blade.php
@extends('layouts.app')

@section('content')
<div class="container">
    <div class="row justify-content-center">
        <div class="col-md-8">
            <div class="card">
                <div class="card-header">Dashboard</div>

                <div class="card-body">
                    @if (session('status'))
                        <div class="alert alert-success" role="alert">
                            {{ session('status') }}
                        </div>
                    @endif

                    You are logged in!
                </div>
            </div>
        </div>
    </div>
</div>
@endsection

root/resources/views/messages.blade.php
@if (session('success'))
    <div class="alert alert-success">
        <span>{{session('success')}}</span>
    </div>
@endif
@if (session('danger'))
    <div class="alert alert-danger">
        <span>{{session('danger')}}</span>
    </div>
@endif
@if ($errors->any())
    <div class="alert alert-danger">
        @foreach ($errors->all() as $error)
            <span>{{$error}}</span>
        @endforeach
    </div>
@endif

root/resources/views/profile.blade.php
@extends('layouts.app')
@section('content')
    <div class="container">
        <div class="row">
            <div class="col-sm-12 col-md-10">
                <h5 class="title">Edit Profile</h5>
            </div>
            <div class="col-sm-12 col-md-2 text-right">
            </div>
        </div>
        <hr>
        <div class="row">
            <div class="col-sm-12 col-md-4">
                <form action="{{route('account.update',[$user])}}" method="post">
                    @csrf
                    <input type="hidden" name="_method" value="PUT">
                    <div class="form-group">
                        <label for="name">Name</label>
                        <input type="text" name="name" id="name" class="form-control" value="{{$user->name}}">
                    </div>
                    <div class="form-group">
                        <label for="email">Email</label>
                        <input type="email" name="email" id="email" class="form-control" value="{{$user->email}}">
                    </div>
                    <div class="form-group">
                        <label for="password">Change Password</label>
                        <input type="password" name="password" id="password" class="form-control">
                    </div>
                    <div class="form-group">
                       <button type="submit" class="btn btn-outline-success">Save</button>
                    </div>
                </form>
            </div>
        </div>
    </div>
@endsection